### PR TITLE
Update to modern idioms and update dependancies

### PR DESCRIPTION
**Pull request by ghost**
Did a cleanup of the gemspec, spec_helper and readme.

I updated the both the dependancies and the development dependancies. Updated the specs to remove deprecations caused by the latest version of RSpec.

My main motivation of this was to allow the dependancy of the json gem to be something other than `~> 1.7.5`. (Namely I wanted to be able to use json 1.8.0 in a project of mine with this in my Gemfile).

This is a pretty big PR relative to the size of the gem so let me know if it's too much and I should die in a :fire:

### CODE REVIEW

**Comment by technicalpickles** [comment]
These look like good changes, but it's a lot easier to merge smaller targeted pull requests. It looks like you switched out jeweler for bundler as part of this. It's probably fine, but probably worth mentioning it as it affects how the gem is released.

I'd also suggest reverting the version bump, as that should be done separate from pull requests.

**Comment by ghost** [comment]
Would you prefer multiple pull requests, or me splitting out the commits in this PR?

**Comment by ghost** [comment]
I didn't bother sending separate PR's as there would be some inconsistent states for each of the above commits (though I did run specs for each commit and they did pass).

I think it makes sense to merge this in as a single merge commit.

**Comment by kirs** [comment]
@Soliah :+1:

**Pull request closed without merging**
